name: Cliente
description: Componente GUI que funciona como un cliente en este sistema utilizando la funcionalidad que realizan los microservicios


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.3.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  fluttertoast: ^8.0.7
  url_launcher: ^6.0.18
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

flutter:

  uses-material-design: true
  assets:
    - .env